#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-ehcache
Version  : 3.3.1
Release  : 1
URL      : https://github.com/ehcache/ehcache3/archive/v3.3.1.tar.gz
Source0  : https://github.com/ehcache/ehcache3/archive/v3.3.1.tar.gz
Source1  : https://repo1.maven.org/maven2/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.jar
Source2  : https://repo1.maven.org/maven2/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-ehcache-data = %{version}-%{release}

%description
= The Ehcache 3.x line is currently the development line.
Status of the build: image:https://ehcache.ci.cloudbees.com/buildStatus/icon?job=ehcache3[Ehcache@Cloudbees, link="https://ehcache.ci.cloudbees.com/job/ehcache3/"]

%package data
Summary: data components for the mvn-ehcache package.
Group: Data

%description data
data components for the mvn-ehcache package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.jar
/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.pom
