#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-ehcache
Version  : 3.3.1
Release  : 3
URL      : https://github.com/ehcache/ehcache3/archive/v3.3.1.tar.gz
Source0  : https://github.com/ehcache/ehcache3/archive/v3.3.1.tar.gz
Source1  : https://repo1.maven.org/maven2/net/sf/ehcache/ehcache-core/2.4.4/ehcache-core-2.4.4.jar
Source2  : https://repo1.maven.org/maven2/net/sf/ehcache/ehcache-core/2.4.4/ehcache-core-2.4.4.pom
Source3  : https://repo1.maven.org/maven2/net/sf/ehcache/ehcache-parent/2.16/ehcache-parent-2.16.pom
Source4  : https://repo1.maven.org/maven2/net/sf/ehcache/ehcache-root/2.8.5/ehcache-root-2.8.5.pom
Source5  : https://repo1.maven.org/maven2/net/sf/ehcache/ehcache/2.4.4/ehcache-2.4.4.pom
Source6  : https://repo1.maven.org/maven2/net/sf/ehcache/ehcache/2.8.5/ehcache-2.8.5.jar
Source7  : https://repo1.maven.org/maven2/net/sf/ehcache/ehcache/2.8.5/ehcache-2.8.5.pom
Source8  : https://repo1.maven.org/maven2/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.jar
Source9  : https://repo1.maven.org/maven2/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-ehcache-data = %{version}-%{release}
Requires: mvn-ehcache-license = %{version}-%{release}

%description
= The Ehcache 3.x line is currently the development line.
Status of the build: image:https://ehcache.ci.cloudbees.com/buildStatus/icon?job=ehcache3[Ehcache@Cloudbees, link="https://ehcache.ci.cloudbees.com/job/ehcache3/"]

%package data
Summary: data components for the mvn-ehcache package.
Group: Data

%description data
data components for the mvn-ehcache package.


%package license
Summary: license components for the mvn-ehcache package.
Group: Default

%description license
license components for the mvn-ehcache package.


%prep
%setup -q -n ehcache3-3.3.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-ehcache
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-ehcache/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-ehcache/NOTICE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-core/2.4.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-core/2.4.4/ehcache-core-2.4.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-core/2.4.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-core/2.4.4/ehcache-core-2.4.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-parent/2.16
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-parent/2.16/ehcache-parent-2.16.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-root/2.8.5
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-root/2.8.5/ehcache-root-2.8.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache/2.4.4
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache/2.4.4/ehcache-2.4.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache/2.8.5
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache/2.8.5/ehcache-2.8.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache/2.8.5
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/net/sf/ehcache/ehcache/2.8.5/ehcache-2.8.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-core/2.4.4/ehcache-core-2.4.4.jar
/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-core/2.4.4/ehcache-core-2.4.4.pom
/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-parent/2.16/ehcache-parent-2.16.pom
/usr/share/java/.m2/repository/net/sf/ehcache/ehcache-root/2.8.5/ehcache-root-2.8.5.pom
/usr/share/java/.m2/repository/net/sf/ehcache/ehcache/2.4.4/ehcache-2.4.4.pom
/usr/share/java/.m2/repository/net/sf/ehcache/ehcache/2.8.5/ehcache-2.8.5.jar
/usr/share/java/.m2/repository/net/sf/ehcache/ehcache/2.8.5/ehcache-2.8.5.pom
/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.jar
/usr/share/java/.m2/repository/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-ehcache/LICENSE
/usr/share/package-licenses/mvn-ehcache/NOTICE
